name: Hosfelt.dev Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.17.1
      - name: build
        run: |
          cd ./themes/boring/
          yarn install --frozen-lockfile
          yarn build
          cd ../../
          zola build
      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./public/*
          host: ${{ secrets.SSH_HOST }}
          remote: ${{ secrets.SSH_DIR }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}